{{- if .Values.fluentd.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grouter.fullname" . }}-fluentd-config
  labels:
    app.kubernetes.io/name: {{ include "grouter.name" . }}-fluentd
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <match *>
      @type opensearch
      host opensearch
      port 9200
      index_name fluentd
      type_name _doc
      logstash_format true
      logstash_prefix fluentd
      logstash_dateformat %Y.%m.%d
      include_tag_key true
      tag_key @log_name
      flush_interval 5s
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "grouter.fullname" . }}-fluentd
  labels:
    app.kubernetes.io/name: {{ include "grouter.name" . }}-fluentd
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grouter.name" . }}-fluentd
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "grouter.name" . }}-fluentd
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: "{{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}"
        ports:
        - containerPort: {{ .Values.fluentd.service.forwardPort }}
          name: forward
        - containerPort: {{ .Values.fluentd.service.httpPort }}
          name: http
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc
      volumes:
      - name: config
        configMap:
          name: {{ include "grouter.fullname" . }}-fluentd-config
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd # Fixed name
  labels:
    app.kubernetes.io/name: {{ include "grouter.name" . }}-fluentd
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.fluentd.service.forwardPort }}
    name: forward
  - port: {{ .Values.fluentd.service.httpPort }}
    name: http
  selector:
    app.kubernetes.io/name: {{ include "grouter.name" . }}-fluentd
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
